services:
  bot:
    platform: linux/amd64  # ← Важно для кросс-платформенной сборки
    build: .
    command: sh -c "sleep 5 && bun run db:migrate && bun run dev"
    volumes:
      - .:/app
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=postgres://dukhov:dukhov@db:5432/racket_mate
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:15-alpine  # ← Alpine-образ для Linux
    platform: linux/amd64      # ← Явно указываем платформу
    environment:
      - POSTGRES_USER=dukhov
      - POSTGRES_PASSWORD=dukhov
      - POSTGRES_DB=racket_mate
    ports:
    - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/00-init.sql
      - ./db/create-user.sql:/docker-entrypoint-initdb.d/01-create-user.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

# Том для хранения данных PostgreSQL
volumes:
  postgres_data: